{% set name = "pyiron_dataclasses" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_dataclasses-{{ version }}.tar.gz
  sha256: 23270dc5825b433da32d8716de49ca70514142b85fc1b2aaa93afd05bc4b7e91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - setuptools
    - versioneer
    - pip
  run:
    - python >=3.9,<3.13

test:
  imports:
    - pyiron_dataclasses
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Dataclasses for the pyiron workflow framework
  home: https://github.com/pyiron/pyiron_dataclasses
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
